name: Generate new icons
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - sandbox

jobs:
  build:
    timeout-minutes: 5
    name: Generate new icons
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update font based on the latest release
        run: |
          RELEASE=$(curl -s "https://api.github.com/repos/lucide-icons/lucide/releases/latest")
          TAG=$(printf "%s" $RELEASE | jq -r .tag_name)
          echo "Latest tag: $TAG" 

          if [ $(git tag -l "$TAG") ]; then
              echo "No changes since the latest release - aborting."
              exit 1
          fi

          URL=$(printf "%s" $RELEASE | jq -r '.assets[] | select(.name | startswith("lucide-font")) | .browser_download_url')

          echo "Downloading $URL" 
          curl -vLJO -H 'Accept: application/octet-stream' $URL
          unzip -o lucide-font-*.zip

          echo "Updating assets"
          mv lucide-font/info.json assets/info.json
          mv lucide-font/lucide.ttf assets/lucide.ttf

          echo "Removing leftovers"
          rm -rf lucide-font
          rm -f lucide-font-*.zip

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Generate icons
        run: dart run tool/generate_fonts.dart

      - name: Push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Release $TAG"
          git push
          git tag 0.3.0
          git push origin 0.3.0
